
CREATE TABLE PERSON
(
    ID           NUMBER PRIMARY KEY,
    NAME         NVARCHAR2(30),
    FAMILY       NVARCHAR2(30),
    USERNAME     NVARCHAR2(20) UNIQUE NOT NULL,
    PASSWORD     NVARCHAR2(20),
    BIRTH_DATE   DATE,
    PHONE_NUMBER NVARCHAR2(15) UNIQUE
);

CREATE SEQUENCE PERSON_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ACCOUNT_INFO
(
    ID               NUMBER PRIMARY KEY,
    PERSON_ID        NUMBER NOT NULL,
    AMOUNT           NUMBER,
    TRANSACTION_TYPE VARCHAR2(7),
    DATE_TIME        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_ACCOUNTINFO_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID)
);

CREATE SEQUENCE TRANSACTION_SEQ START WITH 1 INCREMENT BY 1;

CREATE VIEW TRANSACTION_REPORT AS
SELECT T.ID        AS TRANSACTION_ID,
       P.ID        AS PERSON_ID,
       P.NAME,
       P.FAMILY,
       P.USERNAME,
       P.PASSWORD,
       P.BIRTH_DATE,
       P.PHONE_NUMBER,
       T.AMOUNT,
       T.TRANSACTION_TYPE,
       T.DATE_TIME AS TRANSACTION_DATE_TIME
FROM ACCOUNT_INFO T
         JOIN PERSON P ON T.PERSON_ID = P.ID;

INSERT INTO PERSON (ID, NAME, FAMILY, USERNAME, PASSWORD, BIRTH_DATE, PHONE_NUMBER)
VALUES (PERSON_SEQ.NEXTVAL, 'Reza', 'Mohammadi', 'reza456', 'pass456', DATE '1992-02-02', '09998887766');

INSERT INTO PERSON (ID, NAME, FAMILY, USERNAME, PASSWORD, BIRTH_DATE, PHONE_NUMBER)
VALUES (PERSON_SEQ.NEXTVAL, 'Ali', 'Ahmadi', 'ali123', 'pass123', DATE '1990-01-01', '09123456789');

INSERT INTO ACCOUNT_INFO (ID, PERSON_ID, AMOUNT, TRANSACTION_TYPE)
VALUES (TRANSACTION_SEQ.NEXTVAL, 1, 500000, 'receipt');


SELECT * FROM TRANSACTION_REPORT WHERE ROWNUM = 1;


SELECT *
FROM TRANSACTION_REPORT;
